[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NETLIFY_FORMS_ALLOWED = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Enable form processing
[build.processing]
  skip_processing = false